//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Rhythm Game/Input/CordasVocaisInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CordasVocaisInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CordasVocaisInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CordasVocaisInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""e6baad8d-e1ca-4171-9d21-4e78f0cf70b9"",
            ""actions"": [
                {
                    ""name"": ""ArrowUp"",
                    ""type"": ""Button"",
                    ""id"": ""e8b7fa95-cc00-43b1-af0d-a51115a7f6c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""e541e846-4442-4363-a923-9878f646d095"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""58aaf40f-f32f-4381-912f-124c89ab2c4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""8eb65f5e-7103-4a80-8116-ca24b95656ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8cc37908-e87a-48cd-b254-027522397b4a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba6c3116-488f-47cf-9e99-dde4ec7324e9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19fc921a-aa98-4ad2-9a30-626253291244"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff0789e4-f592-4a5d-b45c-2e539ef6a503"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef31457a-eb0f-4414-88a3-ec2e88151f70"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f8de823-2c4c-44ae-8ef2-4c686501c8a3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baa05f9f-a569-46ea-8b7d-0afa56065591"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1f0995b-3394-497c-8827-6bdaf5f3b066"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ArrowUp = m_Player.FindAction("ArrowUp", throwIfNotFound: true);
        m_Player_ArrowDown = m_Player.FindAction("ArrowDown", throwIfNotFound: true);
        m_Player_ArrowLeft = m_Player.FindAction("ArrowLeft", throwIfNotFound: true);
        m_Player_ArrowRight = m_Player.FindAction("ArrowRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_ArrowUp;
    private readonly InputAction m_Player_ArrowDown;
    private readonly InputAction m_Player_ArrowLeft;
    private readonly InputAction m_Player_ArrowRight;
    public struct PlayerActions
    {
        private @CordasVocaisInputActions m_Wrapper;
        public PlayerActions(@CordasVocaisInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArrowUp => m_Wrapper.m_Player_ArrowUp;
        public InputAction @ArrowDown => m_Wrapper.m_Player_ArrowDown;
        public InputAction @ArrowLeft => m_Wrapper.m_Player_ArrowLeft;
        public InputAction @ArrowRight => m_Wrapper.m_Player_ArrowRight;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @ArrowUp.started += instance.OnArrowUp;
            @ArrowUp.performed += instance.OnArrowUp;
            @ArrowUp.canceled += instance.OnArrowUp;
            @ArrowDown.started += instance.OnArrowDown;
            @ArrowDown.performed += instance.OnArrowDown;
            @ArrowDown.canceled += instance.OnArrowDown;
            @ArrowLeft.started += instance.OnArrowLeft;
            @ArrowLeft.performed += instance.OnArrowLeft;
            @ArrowLeft.canceled += instance.OnArrowLeft;
            @ArrowRight.started += instance.OnArrowRight;
            @ArrowRight.performed += instance.OnArrowRight;
            @ArrowRight.canceled += instance.OnArrowRight;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @ArrowUp.started -= instance.OnArrowUp;
            @ArrowUp.performed -= instance.OnArrowUp;
            @ArrowUp.canceled -= instance.OnArrowUp;
            @ArrowDown.started -= instance.OnArrowDown;
            @ArrowDown.performed -= instance.OnArrowDown;
            @ArrowDown.canceled -= instance.OnArrowDown;
            @ArrowLeft.started -= instance.OnArrowLeft;
            @ArrowLeft.performed -= instance.OnArrowLeft;
            @ArrowLeft.canceled -= instance.OnArrowLeft;
            @ArrowRight.started -= instance.OnArrowRight;
            @ArrowRight.performed -= instance.OnArrowRight;
            @ArrowRight.canceled -= instance.OnArrowRight;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnArrowUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnArrowLeft(InputAction.CallbackContext context);
        void OnArrowRight(InputAction.CallbackContext context);
    }
}
